#164541738 Create verification email template
shop-inc/identity-management pull request #10
Opened 2019-03-13 07:59 UTC by Duncanian

#### What does this PR do?
Sends a pretty verification email to a user after signup
#### Description of Task to be completed?
  - create an email template
  - embed a user's details to the email template when sending it

#### How should this be manually tested?
`yarn test`

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
* [#164541738](https://www.pivotaltracker.com/story/show/164541738)
#### Screenshots (if appropriate)
<img width="527" alt="Screenshot 2019-03-13 at 09 56 23" src="https://user-images.githubusercontent.com/25982160/54262200-acdef700-457e-11e9-903f-4f60425040f1.png">

2019-03-13 15:06 UTC, davenjeru requested changes
There should be a button to send the user to the verification URL.

2019-03-13 15:06 UTC, davenjeru commented on server/helpers/index.ts
> +    return mailTemplate(name);
Where is the verification token passed onto the HTML? @Duncanian

2019-03-13 19:45 UTC, Duncanian commented on server/helpers/index.ts
> +    return mailTemplate(name);
I have added it already.

2019-03-14 14:02 UTC, davenjeru approved these changes

2019-03-14 14:02 UTC, merged